services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api_pw
      POSTGRES_DB: hospital
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  migrations:
    image: migrate/migrate:v4.17.1
    depends_on: [db]
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database",
        "postgres://api:api_pw@db:5432/hospital?sslmode=disable",
        "up",
      ]

  api:
    build: .
    depends_on: [migrations]
    environment:
      - DB_DSN=postgres://api:api_pw@db:5432/hospital?sslmode=disable
      - PORT=8080
      - JWT_SECRET=dev-secret-change-me
    ports: ["8080:8080"]

  nginx:
    image: nginx:1.25-alpine
    depends_on: [api]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: ["80:80"]

volumes:
  db_data:
